// Service Catalog Data - Types and Constants
// This file contains the data definitions for the service catalog.

import type {
  CarePlanTier,
  ServiceGroup,
  ServiceCatalogEntry,
} from './service-catalog-types';

// ── Care Plan Tiers ──

export const CARE_PLAN_TIERS: CarePlanTier[] = [
  {
    id: 'essentials',
    name: 'Essentials',
    price: 19,
    priceLabel: '£19/month',
    tagline: 'Core document maintenance',
    includes: [
      'Monthly document updates',
      'Pricing and service changes',
      'GDPR regulation updates',
    ],
    stripePriceId: { test: 'price_1TqbeiGfxcDbzGRtlwAhDA7i', live: '' },
  },
  {
    id: 'standard',
    name: 'Standard',
    price: 29,
    priceLabel: '£29/month',
    tagline: 'Full support and priority access',
    includes: [
      'Monthly document updates',
      'Pricing and service changes',
      'GDPR regulation updates',
      'Priority support',
      'New document additions',
    ],
    stripePriceId: { test: 'price_1TjIl9GfxcDbzGRtgZxMzBWo', live: '' },
  },
  {
    id: 'complete',
    name: 'Complete',
    price: 49,
    priceLabel: '£49/month',
    tagline: 'Full business infrastructure maintenance',
    includes: [
      'Monthly document updates',
      'Pricing and service changes',
      'GDPR regulation updates',
      'Priority support',
      'New document additions',
      'Social media content refresh',
      'Website copy updates',
    ],
    stripePriceId: { test: 'price_1TqbeiGfxcDbzGRt3pvHkD4h', live: '' },
  },
];

// ── Service Groups (Bundles) ──

export const serviceGroups: ServiceGroup[] = [
  {
    id: 'foundation_bundle',
    name: 'Foundation Bundle',
    description: 'Everything to start your business — documents, website, and social media.',
    serviceIds: ['business_foundations_pack', 'website_copy_pack', 'social_media_pack'],
    discountPercent: 15,
    tier: 'foundation',
    badge: 'Best Value',
  },
  {
    id: 'operations_bundle',
    name: 'Operations Bundle',
    description: 'Protect your business with client onboarding and payment protection.',
    serviceIds: ['client_onboarding_pack', 'payment_protection_pack'],
    discountPercent: 10,
    tier: 'operations',
    badge: null,
  },
  {
    id: 'compliance_bundle',
    name: 'Compliance Bundle',
    description: 'Protect your intellectual property and ensure full GDPR compliance.',
    serviceIds: ['copyright_licensing_pack', 'gdpr_deep_pack'],
    discountPercent: 10,
    tier: 'operations',
    badge: null,
  },
  {
    id: 'full_operations_bundle',
    name: 'Full Operations Bundle',
    description: 'Complete operational protection — onboarding, payments, IP, and GDPR.',
    serviceIds: ['client_onboarding_pack', 'payment_protection_pack', 'copyright_licensing_pack', 'gdpr_deep_pack'],
    discountPercent: 15,
    tier: 'operations',
    badge: 'Most Popular',
  },
  {
    id: 'coach_full_bundle',
    name: 'Coach Complete Bundle',
    description: 'All operations packs plus coach-specific documents and compliance.',
    serviceIds: ['client_onboarding_pack', 'payment_protection_pack', 'copyright_licensing_pack', 'gdpr_deep_pack', 'coach_industry_pack'],
    discountPercent: 20,
    tier: 'industry',
    badge: null,
  },
  {
    id: 'photographer_full_bundle',
    name: 'Photographer Complete Bundle',
    description: 'All operations packs plus photographer-specific documents and compliance.',
    serviceIds: ['client_onboarding_pack', 'payment_protection_pack', 'copyright_licensing_pack', 'gdpr_deep_pack', 'photographer_industry_pack'],
    discountPercent: 20,
    tier: 'industry',
    badge: null,
  },
  {
    id: 'consultant_full_bundle',
    name: 'Consultant Complete Bundle',
    description: 'All operations packs plus consultant-specific documents and compliance.',
    serviceIds: ['client_onboarding_pack', 'payment_protection_pack', 'copyright_licensing_pack', 'gdpr_deep_pack', 'consultant_industry_pack'],
    discountPercent: 20,
    tier: 'industry',
    badge: null,
  },
  {
    id: 'contractor_full_bundle',
    name: 'Contractor Complete Bundle',
    description: 'All operations packs plus contractor-specific documents and H&S compliance.',
    serviceIds: ['client_onboarding_pack', 'payment_protection_pack', 'copyright_licensing_pack', 'gdpr_deep_pack', 'contractor_industry_pack'],
    discountPercent: 20,
    tier: 'industry',
    badge: null,
  },
  {
    id: 'complete_infrastructure_bundle',
    name: 'Complete Infrastructure Bundle',
    description: 'Every pack we offer — the full business infrastructure, built for you.',
    serviceIds: [
      'business_foundations_pack', 'website_copy_pack', 'social_media_pack',
      'client_onboarding_pack', 'payment_protection_pack', 'copyright_licensing_pack', 'gdpr_deep_pack',
      'coach_industry_pack', 'photographer_industry_pack', 'consultant_industry_pack', 'contractor_industry_pack',
    ],
    discountPercent: 25,
    tier: 'industry',
    badge: 'Ultimate',
  },
];

// ── Bundle Discount Tiers ──

export const BUNDLE_DISCOUNT_TIERS = {
  1: { percentage: 0, label: '' },
  2: { percentage: 10, label: '10% bundle discount' },
  3: { percentage: 15, label: '15% bundle discount — best value' },
} as const;

// ── Service Catalog ──

export const serviceCatalog: ServiceCatalogEntry[] = [
  // ── FOUNDATION TIER ──
  {
    id: 'business_foundations_pack',
    name: 'Business Foundations Pack',
    description: 'Complete business foundations pack for UK sole traders — 10 bespoke documents delivered in 24 hours.',
    shortDescription: '10 bespoke business documents — contracts, terms, policies, and more.',
    price: 79.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'payment',
    stripePriceIds: { test: 'price_1TZc9UGfxcDbzGRtniOLIJLE', live: '' },
    stripeProductIds: { test: 'prod_UWOFFYAhQGQ1YM', live: '' },
    includes: [
      'Bespoke Client Contract',
      'Terms & Conditions',
      'GDPR Privacy Policy',
      'Professional Bio',
      'Elevator Pitch (3 versions)',
      'LinkedIn Profile Script',
      'Professional Invoice Template',
      'New Client Welcome Emails (x3)',
      'Late Payment Letters (x3)',
      'Service Description Sheets',
    ],
    requiresIntake: true,
    intakeSections: ['intro', 'business_identity', 'services', 'clients', 'pricing', 'gdpr', 'legal', 'brand', 'invoice', 'linkedin', 'final'],
    isStandalone: true,
    sortOrder: 1,
    isCore: true,
    priceLabel: '£79 — one-time',
    tier: 'foundation',
    industry: null,
    serviceGroup: 'foundation_bundle',
    relatedServiceIds: ['website_copy_pack', 'social_media_pack', 'client_onboarding_pack'],
    badge: 'Best Seller',
  },
  {
    id: 'website_copy_pack',
    name: 'Website Copy Starter Pack',
    description: 'A fully built, ready-to-deploy website created from your brand voice and services — delivered as source files and a hosted preview.',
    shortDescription: 'A fully built website tailored to your brand — ready to deploy.',
    price: 35.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'payment',
    stripePriceIds: { test: 'price_1TgSEkGfxcDbzGRtDaBz70tR', live: '' },
    stripeProductIds: { test: 'prod_UfnqtTGEWkoXYK', live: '' },
    includes: [
      'Homepage (hero, benefits, CTA)',
      'About page',
      'Services page (aligned with your service sheets)',
      'Contact page',
      'FAQ, Blog, Pricing, or Testimonials pages (as needed)',
      'Fully built website — ready to deploy',
      'Website source files (ZIP download)',
      'Hosted preview URL to review before deploying',
    ],
    requiresIntake: true,
    intakeSections: ['intro', 'business_identity', 'services', 'clients', 'brand', 'website_copy', 'final'],
    isStandalone: true,
    sortOrder: 2,
    isCore: false,
    priceLabel: 'From £35 — per page',
    defaultQuantity: 1,
    quantityUnit: 'pages',
    tier: 'foundation',
    industry: null,
    serviceGroup: 'foundation_bundle',
    relatedServiceIds: ['business_foundations_pack', 'social_media_pack'],
    badge: null,
    pricingTiers: [
      { quantity: 1, price: 35, label: '1 page — £35', stripePriceId: { test: 'price_1TgXZQGfxcDbzGRtkovnGBSm', live: '' } },
      { quantity: 2, price: 65, label: '2 pages — £65', stripePriceId: { test: 'price_1TgXZYGfxcDbzGRtnokfBuT3', live: '' } },
      { quantity: 3, price: 90, label: '3 pages — £90', stripePriceId: { test: 'price_1TgXa9GfxcDbzGRtcQYtwDeI', live: '' } },
      { quantity: 4, price: 115, label: '4 pages — £115', stripePriceId: { test: 'price_1TgXbFGfxcDbzGRtuRAV2SGv', live: '' } },
      { quantity: 5, price: 139, label: '5 pages — £139', stripePriceId: { test: 'price_1TgSEkGfxcDbzGRtDaBz70tR', live: '' } },
      { quantity: 6, price: 160, label: '6 pages — £160', stripePriceId: { test: 'price_1TgXbQGfxcDbzGRteGhQeYwJ', live: '' } },
      { quantity: 7, price: 180, label: '7 pages — £180', stripePriceId: { test: 'price_1TgXbZGfxcDbzGRtjlm9GL6Z', live: '' } },
      { quantity: 8, price: 200, label: '8 pages — £200', stripePriceId: { test: 'price_1TgXbhGfxcDbzGRtlqg1FHhk', live: '' } },
      { quantity: 9, price: 218, label: '9 pages — £218', stripePriceId: { test: 'price_1TgXbxGfxcDbzGRtnTF07CE2', live: '' } },
      { quantity: 10, price: 235, label: '10 pages — £235', stripePriceId: { test: 'price_1TgXc3GfxcDbzGRtHs7m8tou', live: '' } },
    ],
  },
  {
    id: 'social_media_pack',
    name: 'Social Media Starter Pack',
    description: 'Done-for-you posts tailored to your industry, audience, and offer. Choose from 5 to 30 posts.',
    shortDescription: 'Done-for-you social posts tailored to your brand and audience.',
    price: 20.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'payment',
    stripePriceIds: { test: 'price_1TgTD4GfxcDbzGRtwfjjKSc9', live: '' },
    stripeProductIds: { test: 'prod_Ufnsr70N1uRKfN', live: '' },
    includes: ['Educational posts', 'Promotional posts', 'Personal / trust-building posts', 'Captions & hashtag suggestions'],
    requiresIntake: true,
    intakeSections: ['intro', 'business_identity', 'services', 'brand', 'social_media', 'final'],
    isStandalone: true,
    sortOrder: 3,
    isCore: false,
    priceLabel: 'From £20 — 5 posts',
    defaultQuantity: 5,
    quantityUnit: 'posts',
    tier: 'foundation',
    industry: null,
    serviceGroup: 'foundation_bundle',
    relatedServiceIds: ['business_foundations_pack', 'website_copy_pack'],
    badge: null,
    pricingTiers: [
      { quantity: 5, price: 20, label: '5 posts — £20', stripePriceId: { test: 'price_1TgTD4GfxcDbzGRtwfjjKSc9', live: '' } },
      { quantity: 10, price: 40, label: '10 posts — £40', stripePriceId: { test: 'price_1TgT9eGfxcDbzGRtZFH9msuO', live: '' } },
      { quantity: 15, price: 57, label: '15 posts — £57', stripePriceId: { test: 'price_1TgTAGGfxcDbzGRtYvH7lEYi', live: '' } },
      { quantity: 20, price: 73, label: '20 posts — £73', stripePriceId: { test: 'price_1TgTAZGfxcDbzGRt6ehHzu2X', live: '' } },
      { quantity: 25, price: 80, label: '25 posts — £80', stripePriceId: { test: 'price_1TgTAwGfxcDbzGRtBoXaKI19', live: '' } },
      { quantity: 30, price: 110, label: '30 posts — £110', stripePriceId: { test: 'price_1TgTCpGfxcDbzGRtmaTlfkcF', live: '' } },
    ],
  },
  {
    id: 'monthly_care_plan',
    name: 'Monthly Care Plan',
    description: 'Keep your documents accurate as your business evolves. Choose your level of support.',
    shortDescription: 'Modular monthly support — pick the plan that fits your business.',
    price: 19.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'subscription',
    stripePriceIds: { test: 'price_1TjIl9GfxcDbzGRtgZxMzBWo', live: '' },
    stripeProductIds: { test: 'prod_UfntRYA1SkzyAD', live: '' },
    includes: [
      'Monthly document updates',
      'Pricing and service changes',
      'GDPR regulation updates',
      'Priority support (Standard+)',
      'New document additions (Standard+)',
      'Social media & website refresh (Complete)',
    ],
    requiresIntake: false,
    intakeSections: [],
    isStandalone: false,
    sortOrder: 50,
    isCore: false,
    subscriptionInterval: 'month',
    priceLabel: 'From £19/month — cancel anytime',
    tier: 'foundation',
    industry: null,
    serviceGroup: null,
    relatedServiceIds: ['business_foundations_pack'],
    badge: null,
  },
  {
    id: 'quarterly_refresh',
    name: 'Quarterly Document Refresh',
    description: 'Keep your documents accurate as your business evolves. Recurring billing every 4 months.',
    shortDescription: 'Quarterly document updates for your business.',
    price: 29.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'subscription',
    stripePriceIds: { test: 'price_1TjIl9GfxcDbzGRtgZxMzBWo', live: '' },
    stripeProductIds: { test: 'prod_UfntRYA1SkzyAD', live: '' },
    includes: ['One document update per quarter', 'Pricing changes', 'New services', 'GDPR updates if needed'],
    requiresIntake: false,
    intakeSections: [],
    isStandalone: false,
    sortOrder: 51,
    isCore: false,
    subscriptionInterval: 'month',
    priceLabel: '£29 every 4 months',
    tier: 'foundation',
    industry: null,
    serviceGroup: null,
    relatedServiceIds: ['business_foundations_pack', 'monthly_care_plan'],
    badge: null,
    hiddenFromCheckout: true,
  },

  // ── OPERATIONS TIER ──
  {
    id: 'client_onboarding_pack',
    name: 'Client Onboarding & Scope Control Pack',
    description: 'Professional onboarding systems that prevent scope creep and set clear expectations.',
    shortDescription: 'Onboarding systems and scope control — protect your time from day one.',
    price: 149.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'payment',
    stripePriceIds: { test: 'price_1TjIeAGfxcDbzGRtAdPjogwV', live: '' },
    stripeProductIds: { test: 'prod_Uik8MyUKPcf5cB', live: '' },
    includes: [
      'Client Onboarding Questionnaire',
      'Scope of Work Document',
      'Project Brief Template',
      'Change Request Form',
      'Onboarding Checklist',
      'Client Communication Protocols',
      'Welcome Packet Guide',
      'Feedback & Closing Questionnaire',
    ],
    requiresIntake: true,
    intakeSections: ['intro', 'business_identity', 'services', 'clients', 'pricing', 'client_onboarding', 'final'],
    isStandalone: true,
    sortOrder: 10,
    isCore: false,
    priceLabel: '£149 — one-time',
    tier: 'operations',
    industry: null,
    serviceGroup: 'operations_bundle',
    relatedServiceIds: ['payment_protection_pack', 'copyright_licensing_pack'],
    badge: 'New',
  },
  {
    id: 'payment_protection_pack',
    name: 'Payment Protection Pack',
    description: 'Comprehensive payment protection system — invoicing terms, late payment recovery, deposit protection.',
    shortDescription: 'Payment protection — invoicing, late payments, deposits, and chargebacks.',
    price: 149.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'payment',
    stripePriceIds: { test: 'price_1TjIf6GfxcDbzGRtv843ka5P', live: '' },
    stripeProductIds: { test: 'prod_Uik9rl1K2wu6yf', live: '' },
    includes: [
      'Invoice Terms & Conditions',
      'Late Payment Policy',
      'Payment Schedule Template',
      'Refund & Cancellation Policy',
      'Deposit & Cancellation Terms',
      'Payment Tracking Template',
      'Chasing Payment Scripts (x5)',
      'Chargeback Response Templates',
    ],
    requiresIntake: true,
    intakeSections: ['intro', 'business_identity', 'services', 'pricing', 'payment_protection', 'final'],
    isStandalone: true,
    sortOrder: 11,
    isCore: false,
    priceLabel: '£149 — one-time',
    tier: 'operations',
    industry: null,
    serviceGroup: 'operations_bundle',
    relatedServiceIds: ['client_onboarding_pack', 'gdpr_deep_pack'],
    badge: null,
  },
  {
    id: 'copyright_licensing_pack',
    name: 'Copyright & Licensing Pack',
    description: 'Protect your intellectual property — copyright notices, licensing agreements, NDAs.',
    shortDescription: 'IP protection — copyright, licensing, NDAs, and brand usage.',
    price: 149.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'payment',
    stripePriceIds: { test: 'price_1TjIfpGfxcDbzGRt1rBiLXqC', live: '' },
    stripeProductIds: { test: 'prod_UikA7BHcffvw7C', live: '' },
    includes: [
      'Copyright Notice & IP Policy',
      'Content Licensing Agreement',
      'Image & Media Usage Rights',
      'Work-for-Hire Agreement',
      'Brand Usage Guidelines',
      'Non-Disclosure Agreement (NDA)',
      'IP Assignment Agreement',
      'Cease & Desist Template',
    ],
    requiresIntake: true,
    intakeSections: ['intro', 'business_identity', 'services', 'copyright_licensing', 'final'],
    isStandalone: true,
    sortOrder: 12,
    isCore: false,
    priceLabel: '£149 — one-time',
    tier: 'operations',
    industry: null,
    serviceGroup: 'compliance_bundle',
    relatedServiceIds: ['payment_protection_pack', 'gdpr_deep_pack'],
    badge: null,
  },
  {
    id: 'gdpr_deep_pack',
    name: 'GDPR & Data Retention Deep Pack',
    description: 'Beyond the basic privacy policy — comprehensive GDPR compliance.',
    shortDescription: 'Deep GDPR compliance — DPAs, breach response, consent, and retention.',
    price: 199.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'payment',
    stripePriceIds: { test: 'price_1TjIgyGfxcDbzGRt3O0f8wmM', live: '' },
    stripeProductIds: { test: 'prod_UikBCrjnKNO4G3', live: '' },
    includes: [
      'Comprehensive Privacy Policy',
      'Data Retention Schedule',
      'Data Processing Agreement (DPA)',
      'Cookie Consent Implementation Guide',
      'Subject Access Request Template',
      'Data Breach Notification Template',
      'Data Protection Impact Assessment (DPIA)',
      'Marketing Consent Management Procedures',
      'Third-Party Data Sharing Agreement',
    ],
    requiresIntake: true,
    intakeSections: ['intro', 'business_identity', 'gdpr', 'gdpr_deep', 'final'],
    isStandalone: true,
    sortOrder: 13,
    isCore: false,
    priceLabel: '£199 — one-time',
    tier: 'operations',
    industry: null,
    serviceGroup: 'compliance_bundle',
    relatedServiceIds: ['copyright_licensing_pack', 'payment_protection_pack'],
    badge: 'Essential',
  },

  // ── INDUSTRY TIER ──
  {
    id: 'coach_industry_pack',
    name: 'Coach Industry Pack',
    description: 'Industry-specific documents for coaches — coaching agreements, session terms, ethical standards.',
    shortDescription: 'Coaching-specific documents — agreements, ethics, and CPD tracking.',
    price: 199.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'payment',
    stripePriceIds: { test: 'price_1TjIhfGfxcDbzGRtWDo6RyZ6', live: '' },
    stripeProductIds: { test: 'prod_UikCoQ27voUDgH', live: '' },
    includes: [
      'Coaching Agreement',
      'Session Terms & Cancellation Policy',
      'Supervision Policy',
      'CPD Tracker Template',
      'Coaching Code of Ethics',
      'Client Progress Tracker',
      'Testimonial Request Template',
    ],
    requiresIntake: true,
    intakeSections: ['intro', 'business_identity', 'services', 'clients', 'brand', 'industry_coach', 'final'],
    isStandalone: true,
    sortOrder: 20,
    isCore: false,
    priceLabel: '£199 — one-time',
    tier: 'industry',
    industry: 'coach',
    serviceGroup: 'coach_full_bundle',
    relatedServiceIds: ['client_onboarding_pack', 'payment_protection_pack', 'copyright_licensing_pack'],
    badge: null,
  },
  {
    id: 'photographer_industry_pack',
    name: 'Photographer Industry Pack',
    description: 'Industry-specific documents for photographers — licensing, model releases, delivery terms.',
    shortDescription: 'Photographer-specific documents — licensing, releases, and delivery terms.',
    price: 249.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'payment',
    stripePriceIds: { test: 'price_1TjIiFGfxcDbzGRt74btRoIa', live: '' },
    stripeProductIds: { test: 'prod_UikC8e74WJiQmR', live: '' },
    includes: [
      'Photography Licensing Agreement',
      'Model Release Form',
      'Shot List Template',
      'Delivery Terms & Timeline Policy',
      'Editing Brief Template',
      'Print Release Form',
      'Event Photography Terms',
    ],
    requiresIntake: true,
    intakeSections: ['intro', 'business_identity', 'services', 'clients', 'brand', 'industry_photographer', 'final'],
    isStandalone: true,
    sortOrder: 21,
    isCore: false,
    priceLabel: '£249 — one-time',
    tier: 'industry',
    industry: 'photographer',
    serviceGroup: 'photographer_full_bundle',
    relatedServiceIds: ['copyright_licensing_pack', 'gdpr_deep_pack', 'payment_protection_pack'],
    badge: null,
  },
  {
    id: 'consultant_industry_pack',
    name: 'Consultant Industry Pack',
    description: 'Industry-specific documents for consultants — consulting agreements, deliverables specs.',
    shortDescription: 'Consultant-specific documents — agreements, deliverables, and handover.',
    price: 199.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'payment',
    stripePriceIds: { test: 'price_1TjIj6GfxcDbzGRtazMtGvDM', live: '' },
    stripeProductIds: { test: 'prod_UikD7l5dus5Mps', live: '' },
    includes: [
      'Consulting Agreement',
      'Consultant NDA',
      'Deliverables Specification',
      'Milestone Tracking Template',
      'Knowledge Transfer Protocol',
      'Consultant Code of Conduct',
      'Engagement Closure Report',
    ],
    requiresIntake: true,
    intakeSections: ['intro', 'business_identity', 'services', 'clients', 'brand', 'industry_consultant', 'final'],
    isStandalone: true,
    sortOrder: 22,
    isCore: false,
    priceLabel: '£199 — one-time',
    tier: 'industry',
    industry: 'consultant',
    serviceGroup: 'consultant_full_bundle',
    relatedServiceIds: ['client_onboarding_pack', 'copyright_licensing_pack', 'payment_protection_pack'],
    badge: null,
  },
  {
    id: 'contractor_industry_pack',
    name: 'Contractor Industry Pack',
    description: 'Industry-specific documents for contractors — H&S policy, risk assessments, method statements.',
    shortDescription: 'Contractor-specific documents — H&S, risk assessments, and CDM compliance.',
    price: 299.0,
    currency: 'gbp',
    currencySymbol: '£',
    mode: 'payment',
    stripePriceIds: { test: 'price_1TjIjmGfxcDbzGRtDlS8hipL', live: '' },
    stripeProductIds: { test: 'prod_UikEWm8W32KbVv', live: '' },
    includes: [
      'Health & Safety Policy',
      'Risk Assessment Template',
      'Method Statement',
      'COSHH Assessment',
      'Construction Phase Plan',
      'Subcontractor Agreement',
      'Site Induction Checklist',
      'Defect Liability Template',
    ],
    requiresIntake: true,
    intakeSections: ['intro', 'business_identity', 'services', 'clients', 'brand', 'industry_contractor', 'final'],
    isStandalone: true,
    sortOrder: 23,
    isCore: false,
    priceLabel: '£299 — one-time',
    tier: 'industry',
    industry: 'contractor',
    serviceGroup: 'contractor_full_bundle',
    relatedServiceIds: ['gdpr_deep_pack', 'payment_protection_pack', 'client_onboarding_pack'],
    badge: null,
  },
];
