import type { DbProposal } from './db';

// ---------------------------------------------------------------------------
// Physical mail integration (Phase 44).
// The print & post provider (Pingen) lives entirely behind this module plus
// POST /api/proposals/[id]/send — the frontend only ever sees "send this
// proposal" and the resulting delivery state. When provider credentials are
// not configured, dispatch runs in local mode: the delivery state machine is
// simulated exactly like the real flow (tracking number + estimated delivery),
// so the frontend behaves identically in development.
// ---------------------------------------------------------------------------

const PINGEN_API_URL = 'https://api.pingen.com/v2';

export interface MailDispatchResult {
  provider: 'pingen' | 'local';
  trackingNumber: string;
  estimatedDeliveryDate: string;
}

/** Error whose message is safe to show to end users. */
export class MailDispatchError extends Error {
  status: number;

  constructor(message: string, status = 502) {
    super(message);
    this.status = status;
  }
}

export function isMailProviderConfigured(): boolean {
  return Boolean(process.env.PINGEN_API_TOKEN && process.env.PINGEN_ORGANISATION_ID);
}

// UK postcode (e.g. "HP20 1UG", "W1A 0AX", "EC1A1BB").
const UK_POSTCODE_RE = /^([A-Z]{1,2}\d[A-Z\d]?)\s*(\d[A-Z]{2})?$/i;

/** True when the input is shaped like a postcode but is not a valid one. */
export function looksLikeInvalidPostcode(input: string): boolean {
  const value = input.trim();
  if (!value) return false;
  // Starts like an outward code (letter + digit) but doesn't match fully.
  if (/^[A-Z]{1,2}\d/i.test(value)) return !UK_POSTCODE_RE.test(value);
  return false;
}

export function isValidUkPostcode(input: string): boolean {
  return UK_POSTCODE_RE.test(input.trim());
}

function localTrackingNumber(): string {
  return `RM-TRK-${Math.floor(Math.random() * 900000 + 100000)}`;
}

/**
 * Dispatch a proposal document by post. Throws MailDispatchError with a
 * user-safe message on failure — callers must never leak provider internals.
 */
export async function dispatchProposalMail(proposal: DbProposal): Promise<MailDispatchResult> {
  if (!proposal.recipientName || !proposal.recipientAddress || !proposal.recipientPostcode) {
    throw new MailDispatchError('Recipient name, address and postcode are required.', 400);
  }
  if (!isValidUkPostcode(proposal.recipientPostcode)) {
    throw new MailDispatchError(
      'The delivery postcode looks invalid. Please check it and try again.',
      400
    );
  }

  if (!isMailProviderConfigured()) {
    // Local mode: simulated dispatch with a realistic delivery estimate.
    const est = new Date();
    est.setDate(est.getDate() + 3);
    return {
      provider: 'local',
      trackingNumber: localTrackingNumber(),
      estimatedDeliveryDate: est.toISOString(),
    };
  }

  try {
    // Pingen letter dispatch: the proposal reference + recipient address are
    // sent for print & post. Only this module knows the provider exists.
    const response = await fetch(
      `${PINGEN_API_URL}/organisations/${process.env.PINGEN_ORGANISATION_ID}/letters`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${process.env.PINGEN_API_TOKEN}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: `Proposal ${proposal.reference}`,
          address: `${proposal.recipientName}\n${proposal.recipientAddress}\n${proposal.recipientPostcode}`,
          country: 'GB',
          // The proposal document is generated by the frontend preview;
          // Pingen accepts the rendered document as a file upload.
          file: {
            name: `${proposal.reference || 'proposal'}.pdf`,
            // documentUrl is set by the caller when a hosted document exists.
            url: (proposal as { documentUrl?: string }).documentUrl ?? undefined,
          },
          dispatch: 'upload',
        }),
        signal: AbortSignal.timeout(15000),
      }
    );

    if (!response.ok) {
      throw new Error(`provider responded ${response.status}`);
    }

    const data = (await response.json()) as {
      data?: { id?: string; tracking?: { number?: string } };
    };

    const est = new Date();
    est.setDate(est.getDate() + 3);
    return {
      provider: 'pingen',
      trackingNumber: data.data?.tracking?.number || data.data?.id || localTrackingNumber(),
      estimatedDeliveryDate: est.toISOString(),
    };
  } catch (err) {
    const timeout = err instanceof Error && err.name === 'TimeoutError';
    throw new MailDispatchError(
      timeout
        ? 'Our print & post partner took too long to respond. Nothing has been charged — please try again.'
        : 'We could not reach our print & post partner. Nothing has been charged — please try again in a moment.'
    );
  }
}
